### ISSUE TITLE
Can you add a proper readme and a guide on how to use this ?

### ISSUE THREAD

**Issue by NomadXD** [Fullstak-nl/medusa-plugin-postmark#1]

**Comment by Fullstak-nl** [comment]
I will add a getting started with a simple walk through.
Thanks for bringing it up :)

**Comment by NomadXD** [comment]
@Fullstak-nl Thanks and it'll be really helpful for people using this plugin.  I installed the plugin and configured `medusa-config.js` with the code snippet you provided (removed unnecessary values as follows). I set up POSTMARK_SERVER_API with postmark server API token, POSTMARK_FROM with my postmark email and POSTMARK_ORDER_PLACED with the relevant template id in postmark. But still it does not send the email. Anything else to configure ? 

```js
{
    resolve: `medusa-plugin-postmark`,
    options: {
      server_api: process.env.POSTMARK_SERVER_API,
      from: process.env.POSTMARK_FROM,
      events: {
        order: {
          placed: process.env.POSTMARK_ORDER_PLACED || null,
          canceled: process.env.POSTMARK_ORDER_CANCELED || null,
          shipment_created: process.env.POSTMARK_ORDER_SHIPMENT_CREATED || null,
        },
        customer: {
          created: process.env.POSTMARK_CUSTOMER_CREATED || null,
          password_reset: process.env.POSTMARK_CUSTOMER_PASSWORD_RESET || null,
        },
        user: {
          password_reset: process.env.POSTMARK_USER_PASSWORD_RESET || null,
        },
      },
      default_data: {
        // ... default data to be passed to the email template
        product_url: process.env.POSTMARK_PRODUCT_URL || "",
        product_name: process.env.POSTMARK_PRODUCT_NAME || "",
        company_name: process.env.POSTMARK_COMPANY_NAME || "",
        company_address: process.env.POSTMARK_COMPANY_ADDRESS || "",
      },
    },
  },
```

**Comment by Fullstak-nl** [comment]
Do you run redis for the events? 
And did you set the correct template id for your email?

POSTMARK_ORDER_PLACED needs to be set to a postmark template that will be sent when an order is placed.

**Comment by NomadXD** [comment]
@Fullstak-nl I did not run a redis. Thought they have an event bus for development purposes. Is it required to run a redis ? I set up the template id correctly

**Comment by Fullstak-nl** [comment]
I noticed events are not fired sometimes when redis isnt used. 
Could you please check with redis enabled?

**Comment by Fullstak-nl** [comment]
You are most welcome :)
