### ISSUE TITLE
Gift Cards

### ISSUE THREAD

**Issue by huotarih** [Fullstak-nl/medusa-plugin-postmark#2]
A great addition would be the support for gift cards.
Currently it fails because the event doesn't seem to have the "to" field set.

Here's an example gift card object:
`GiftCard {
  id: 'gift_01HCB664Y9SACW0ZYSXQCCDA9Z',
  created_at: 2023-10-09T21:41:13.797Z,
  updated_at: 2023-10-09T21:41:13.797Z,
  deleted_at: null,
  code: 'CODE-CODE-CODE-CODE',
  value: 12300,
  balance: 12300,
  region_id: 'reg_01GZVYCK7YGCE83ATV4C2NF73V',
  order_id: null,
  is_disabled: false,
  ends_at: null,
  tax_rate: 20,
  metadata: { email: 'test@test.com', personal_message: 'test' }
} `

**Comment by breakerh** [comment]
Sorry @huotarih seems like I missed your notification.
I will look into it this week and push a fix for this.

Thanks for letting me know.

**Comment by breakerh** [comment]
At first glance I don't see why an order would fail with a giftcard. And our shop also has payments with partial or full payment with giftcards. Can you explain what went wrong?

**Comment by huotarih** [comment]
This is not an issue with using gift cards or anything like that, the gift cards work just fine. I made the issue inside the postmark plugin repo, because the issue is that I can't send a gift card from admin with postmark. 

To clarify: order doesn't fail, nothing to do with orders. 
I have added an event to my medusa.config ` gift_card: {
                  created: process.env.POSTMARK_GIFT_CARD_CREATED || null,
                }`
And the corresponding template.

<img width="717" alt="Screenshot 2023-10-29 at 22 38 53" src="https://github.com/Fullstak-nl/medusa-plugin-postmark/assets/7366986/069df987-dcb3-4e25-b8c6-e45d60aec9a9">

Maybe this is an issue with medusa? I'm quite not sure. I did fix this by using my own email service for gift cards, like this:
<img width="731" alt="Screenshot 2023-10-29 at 22 41 58" src="https://github.com/Fullstak-nl/medusa-plugin-postmark/assets/7366986/e94915ea-7976-424e-9053-f72156b29401">

**Comment by breakerh** [comment]
Hey @huotarih ,

I will release a new update this week which will include a bunch of extra events. Including the gift card create event :)

**Comment by huotarih** [comment]
Awesome, great to hear @breakerh. Really appreciate your work!

**Comment by breakerh** [comment]
Sorry for the late reply, i've added the gift card event for now.
Will try to expand it asap with more events and thinking about a PDF attachment for gift cards to send a PDF gift card maybe..

I will leave the issue open for a few days maybe there will be feedback etc..
