### ISSUE TITLE
Bug after upgrading to Medusa v1.18.0

### ISSUE THREAD

**Issue by JeffYYW** [Fullstak-nl/medusa-plugin-postmark#3]
Hi all,

Thanks for working on this plugin, it's has been working well but, I'm now getting this error after upgrading medusa to v1.18.0. Am I missing any additional configs?

`error:   Error starting server`
`AwilixResolutionError: Could not resolve 'GiftCardService'.`

This is my current config file:
```
{
    resolve: `medusa-plugin-postmark`,
    options: {
      server_api: process.env.POSTMARK_SERVER_API,
      from: process.env.POSTMARK_FROM,
      events: {
        order: {
          placed: process.env.POSTMARK_ORDER_PLACED || null,
          canceled: process.env.POSTMARK_ORDER_CANCELED || null,
          shipment_created: process.env.POSTMARK_ORDER_SHIPMENT_CREATED || null,
        },
        customer: {
          created: process.env.POSTMARK_CUSTOMER_CREATED || null,
          password_reset: process.env.POSTMARK_CUSTOMER_PASSWORD_RESET || null,
        },
        user: {
          password_reset: process.env.POSTMARK_USER_PASSWORD_RESET || null,
        },
      },
      default_data: {
        product_url: process.env.POSTMARK_PRODUCT_URL || "",
        product_name: process.env.POSTMARK_PRODUCT_NAME || "",
        company_name: process.env.POSTMARK_COMPANY_NAME || "",
        company_address: process.env.POSTMARK_COMPANY_ADDRESS || "",
      },
    },
  },
```

**Comment by sstackus** [comment]
+1

**Comment by thoward27** [comment]
I'm also seeing this on the latest version of medusa with the latest version of this plugin.

**Comment by thoward27** [comment]
@breakerh I'd be happy to try and dig into this to get this resolved, but I don't really know where to start. Do you have any ideas I could pursue? I really want to get Medusa + Postmark up and running

**Comment by breakerh** [comment]
Hey all,

Sorry for the late response! Had some busy weeks including the holidays.
Won't happen again!

Added new release (also in npm) https://github.com/Fullstak-nl/medusa-plugin-postmark/releases/tag/v4.5.1
