### ISSUE TITLE
Add more events

### ISSUE THREAD

**Issue by ralphSOptidist** [Fullstak-nl/medusa-plugin-postmark#5]
`{
               auth: {
                    password_reset: process.env.POSTMARK_PASSWORD_RESET || null,
                    verify_account: process.env.POSTMARK_VERIFY_ACCOUNT || null,
                },
               user: {
                    created: process.env.POSTMARK_WELCOME_USER || null,   //this after registration
                },
               activity: {
                    inactive_user: process.env.POSTMARK_INACTIVE_USER || null,   //to check with the user when the last time he logged in
                    inactive_customer: process.env.POSTMARK_INACTIVE_CUSTOMER || null,
                },
}
`

**Comment by breakerh** [comment]
Just released https://github.com/Fullstak-nl/medusa-plugin-postmark/releases/tag/v4.6.0
This includes your events
